apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization


resources:
  - ../../base

namespace: apps-stg
nameSuffix: -stg

images:
- name: nginx
  newName: my-registry/nginx
  newTag: v1

replicas:
- name: nginx
  count: 5

commonLabels:
  env: stg
