apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - deployment.yaml
  - service.yaml

# secretGenerator:
#   - name: env_file_secret
#     envs:
#     - secrets.txt
#     type: Opaque

# configMapGenerator:
# - name: nginxconfig
#   files:
#   - nginx.conf
  
# images:
# - name: nginx
#   newName: my-registry/nginx
#   newTag: v1
images:
- name: nginx
  newTag: 1.17.7

